483759/Next-Place

backend/src/main/java/com/aespa/nextplace/model/entity/BaseAddress.java, backend/src/main/java/com/aespa/nextplace/model/entity/BaseTimeEntity.java, backend/src/main/java/com/aespa/nextplace/model/entity/City.java, backend/src/main/java/com/aespa/nextplace/model/entity/Plaction.java, backend/src/main/java/com/aespa/nextplace/model/entity/Pladex.java, backend/src/main/java/com/aespa/nextplace/model/entity/Plamon.java, backend/src/main/java/com/aespa/nextplace/model/entity/PlamonRank.java, backend/src/main/java/com/aespa/nextplace/model/entity/Spot.java, backend/src/main/java/com/aespa/nextplace/model/entity/SpotType.java, backend/src/main/java/com/aespa/nextplace/model/entity/User.java, backend/src/main/java/com/aespa/nextplace/model/entity/UserRole.java
- 객체들의 연관관계를 기준으로 엔티티를 초기 설계했습니다.
- 엔티티 설계 후 Embedded H2로 테이블을 생성했을 때, MySQL 테이블과 동일한 형태를 얻고자 했습니다.
<br>
- 생성된 H2의 테이블입니다
- 정해져 있는 상수값을 가지는 String 필드의 경우 Enum으로 선언했습니다.
<br>
- MySQL 테이블과 비교하면서 검토하고 리뷰해주세요
=> feat:[#6] 엔티티 초기 설계

backend/build.gradle, backend/src/main/java/com/aespa/nextplace/config/FirebaseInitializer.java, backend/src/main/java/com/aespa/nextplace/config/SecurityConfig.java, backend/src/main/java/com/aespa/nextplace/controller/UserController.java, backend/src/main/java/com/aespa/nextplace/model/entity/MyUserDetails.java, backend/src/main/java/com/aespa/nextplace/model/entity/User.java, backend/src/main/java/com/aespa/nextplace/model/repository/UserRepository.java, backend/src/main/java/com/aespa/nextplace/response/UserResponse.java, backend/src/main/java/com/aespa/nextplace/service/MyUserDetailsService.java, backend/src/main/java/com/aespa/nextplace/service/UserService.java, backend/src/main/java/com/aespa/nextplace/service/UserServiceImpl.java, backend/src/main/java/com/aespa/nextplace/util/CookieUtil.java, backend/src/main/java/com/aespa/nextplace/util/FirebaseTokenFilter.java
- Google 아이디를 통한 로그인 기능
- 최초 로그인한 유저 회원가입 기능
<br>
- SpringSecurity에 대한 기본적인 설정이 들어갔습니다.
- Firebase의 Token 값을 검증하기 위한 filter를 생성했습니다.
- 'token'이라는 이름으로 헤더에서 토큰을 추출하여 토큰의 유효 상태를 확인하고 있습니다.
- UserRepository와 UserController, UserService를 생성했습니다.
- token의 경우 Cookie에 Httponly, Secure 옵션을 설정하여 들어가고 있습니다.
- Firebase와 연결할 때 필요한 dependency를 추가했습니다.
<br>
- 테스트 코드를 아직 작성하지 못해서 테스트 코드는 추후에 작업할 예정입니다.
=> feat:[#11]:login

backend/build.gradle
- 의존성을 추가했습니다
<br>
- build.gradle에 dependency 추가
<br>
=> fix/dependency 

backend/build.gradle, backend/src/main/java/com/aespa/nextplace/controller/PladexController.java, backend/src/main/java/com/aespa/nextplace/model/entity/Pladex.java, backend/src/main/java/com/aespa/nextplace/model/repository/PladexRepository.java, backend/src/main/java/com/aespa/nextplace/model/request/PladexDtoAssembler.java, backend/src/main/java/com/aespa/nextplace/model/request/PladexRequest.java, backend/src/main/java/com/aespa/nextplace/service/PladexService.java, backend/src/main/java/com/aespa/nextplace/service/PladexServiceImpl.java, backend/src/test/java/com/aespa/nextplace/plamon/PladexServiceTest.java, backend/src/test/java/com/aespa/nextplace/plamon/PlamonServiceTest.java
- 새로운 플레몬을 등록하기 위한 기능을 구현했습니다
<br>
- Request DTO를 Entity로 변환시켜주는 부분이 필요한데, 이는 Request DTO와 Entity 어느 클래스에도 들어가지 않는 것이 좋다고 생각해서 새로운 클래스의 static method로 만들어주었습니다.
- 등록하려는 Plamon과 동일한 이름이 이미 등록되어 있을 경우 등록이 거절됩니다.
- Pladex의 빌더를 수정했습니다.
- 저장/수정/삭제의 경우 Service 메서드에 `@Transactional` 어노테이션이 붙어야 합니다.
<br>
- 컨트롤러에서 이미 존재하는 플레몬일 경우에 어떤 상태코드를 반환하는 게 맞을까요?
- 캐릭터의 사진에 관련된 S3 추가 기능 및 필드는 구현 예정입니다
=> Close #38 Feature/add pladex

backend/src/main/java/com/aespa/nextplace/controller/PlamonController.java, backend/src/main/java/com/aespa/nextplace/model/entity/Plamon.java, backend/src/main/java/com/aespa/nextplace/model/entity/User.java, backend/src/main/java/com/aespa/nextplace/model/repository/PladexRepository.java, backend/src/main/java/com/aespa/nextplace/model/response/ErrorResponse.java, backend/src/main/java/com/aespa/nextplace/service/PlamonService.java, backend/src/main/java/com/aespa/nextplace/service/PlamonServiceImpl.java, backend/src/test/java/com/aespa/nextplace/plamon/PlamonServiceTest.java
- 위의 이슈에서 언급한 것 처럼, 캐릭터를 구매하는 기능을 계획했습니다
- 사용자의 골드와 연결해서 골드가 부족하면 캐릭터 뽑기를 불가능하게 하려고 했습니다
- 등급 별로 뽑기 확률을 랜덤하게 적용했습니다
- 조금 넉넉하게 확률을 잡았습니다 (N - 40%, R - 30%, SR - 20%, SSR - 10%)
<br>
- `User` 엔티티에 골드가 충분한지 검증, 입력한 골드 수를 차감하는 메서드를 추가했습니다
- 비즈니스 로직은 유저 인증 -> 골드 확인 -> 랜덤 캐릭터 뽑기 -> 유저 플레몬 저장 -> 골드 차감 순으로 진행됩니다
- 메서드가 너무 커지는 것을 방지하기 위해 서비스 클래스 내에서 메서드를 분리했습니다
- 랜덤 캐릭터 뽑기는 1️⃣ 확률에 따라 뽑을 랭크를 정하고, 2️⃣ 해당 랭크의 캐릭터가 있는지 우선 검증한 뒤, 3️⃣  특정 랭크에서 랜덤으로 뽑아서 반환하는 식으로 이루어집니다
- 한 유저가 여러 개의 캐릭터를 소유할 수 있습니다
- 처음에는 레벨 1, 경험치 0, 기본 이름으로 캐릭터가 초기화됩니다
<br>
- 리뷰해주시고 나면 불필요한 주석 삭제하겠습니다
- 에러 메시지를 반환하는 부분에서 다음과 같은 메시지가 뜨는 것을 봐서, 메시지를 JSON으로 감싸서 보내야할 것 같은데 어떻게 생각하시나요 
- 에러 반환용으로 String 필드를 가진 DTO를 하나 만드는 것도 좋을 것 같습니다
- 설명 부족한 부분 있으면 코멘트 달아주세요 다음부터는 작은 PR 만들겠습니다 😭
=> Close #45 Feature/buy plamon

backend/src/main/java/com/aespa/nextplace/config/SecurityConfig.java, backend/src/main/java/com/aespa/nextplace/config/TomcatWebServerConfiguration.java, backend/src/main/java/com/aespa/nextplace/controller/PlamonController.java, backend/src/main/java/com/aespa/nextplace/model/repository/PlamonRepository.java, backend/src/main/java/com/aespa/nextplace/service/PlamonService.java, backend/src/main/java/com/aespa/nextplace/service/PlamonServiceImpl.java, backend/src/test/java/com/aespa/nextplace/plamon/PladexServiceTest.java, backend/src/test/java/com/aespa/nextplace/plamon/PlamonServiceTest.java
- 실제 UI 상에서 페이지네이션을 구현해서 조회할 예정이기 때문에 기존의 조회 로직을 수정하고자 햇습니다
<br>
- 기존의 API는 전체 조회가 필요할 수 있을 것 같아 Request URI Path만 변경했습니다
- 페이지네이션을 적용한 조회에는 page, size, sort(기본 제공)가 필요합니다
- 
<br>
- SQL 쿼리문에 sort를 이용해서 내가 가지지 않은 캐릭터 리스트도 후순위로 정렬해서 뽑아올 수 있을지 고민중입니다
=> Close #56 - 캐릭터 조회 기능에 페이지네이션 추가

backend/src/test/java/com/aespa/nextplace/plaction/PlactionServiceTest.java
- 테스트 코드 리팩토링
<br>
- 필요하지 않은 mocking 제거
<br>
=> plaction 테스트 코드 수정

backend/src/main/java/com/aespa/nextplace/config/WebConfiguration.java
- ![image](https://user-images.githubusercontent.com/30489264/141389987-fd85c83a-3c21-41b5-bbf1-147879c76ad0.png)
- Swagger가 TypeError가 발생합니다
<br>
- Cors 허용 오리진에 `http://k5b106.p.ssafy.io`를 추가했습니다
<br>
- 과연 될까요?
=> fix:[#72] CORS Origin 추가

backend/src/main/java/com/aespa/nextplace/config/WebConfiguration.java
- Swagger에 CORS 관련 이슈 발생
<br>
- Request에 대한 Header 및 Method와 같은 각종 설정 추가
<br>
- 되라 🙏
=> fix:[#72] swagger detail 설정

backend/src/main/java/com/aespa/nextplace/config/WebConfiguration.java
- https://stackoverflow.com/questions/45677048/how-do-i-enable-cors-headers-in-the-swagger-v2-api-docs-offered-by-springfox-sw
- 위 링크를 참고해서 CORS 필터를 적용해봤습니다
- 이전 프로젝트에서도 유사하게 CORS 필터를 적용한 부분이 있길래 이 이유이길 간절히 바래봅니다
<br>
- CORS Filter 추가
<br>
- 안되면 스웨거 버리고 포스트맨으로 갈아타기 .... 과연 🙏
=> fix:[#72] cors filter 적용

backend/src/main/java/com/aespa/nextplace/util/NaverMapUtil.java
- MapUtil 키 값 노출 제거
<br>
- MapUtil에 노출 되어 있는 키 값들을 제거 했습니다
<br>
- 테스트용으로 썻던 키 값을 미쳐 확인하지 못하고 넣어서 올렸습니다. 키는 PR 전에 만료 시켰고, 새로 받은 키 값을 집어넣겠습니다.
=> Cloes - #87 fix:[#87] MapUtil에 key값 노출된 것 제거

backend/src/main/java/com/aespa/nextplace/controller/PlactionController.java, backend/src/main/java/com/aespa/nextplace/model/entity/User.java, backend/src/main/java/com/aespa/nextplace/model/response/PlactionUpdateResponse.java, backend/src/main/java/com/aespa/nextplace/service/PlactionService.java, backend/src/main/java/com/aespa/nextplace/service/PlactionServiceImpl.java, backend/src/test/java/com/aespa/nextplace/plaction/PlactionServiceTest.java
-  Plaction 갱신 시 골드 획득 
- 갱신 Response에 획득 골드 표시
<br>
- Plaction 갱신 시 PlactionResponse에서 PlactionUpdateResponse로 변경하였습니다
- Response가 변경되면서 테스트 코드도 수정 되었습니다.
- User Entity에 유저의 골드를 늘리는 earnGold 함수가 추가 되었습니다.
<br>
-
=> Closes #89 - feat:[#89] Plaction 갱신 시 골드 획득

backend/src/main/java/com/aespa/nextplace/model/repository/PladexRepository.java, backend/src/main/java/com/aespa/nextplace/model/repository/PlamonRepository.java, backend/src/main/java/com/aespa/nextplace/service/PlamonServiceImpl.java, backend/src/test/java/com/aespa/nextplace/plamon/PlamonRepositoryTest.java, backend/src/test/java/com/aespa/nextplace/plamon/PlamonServiceTest.java
- 기본 캐릭터를 조회하는 메서드가 Plamon이어서 오류가 발생했습니다
<br>
- 기본 캐릭터를 조회하는 메서드를 Pladex로 옮겼습니다
- 대표 캐릭터 조회 결과가 한 개 이상이면 에러가 발생할 수 있는 문제를 고쳤습니다
<br>
- PR 보내기 전에 전체 테스트 실행해보기..... 명심하겠습니다
=> Fix #91 - 대표 캐릭터 조회

backend/src/main/java/com/aespa/nextplace/config/SecurityConfig.java, backend/src/main/java/com/aespa/nextplace/controller/UserController.java, backend/src/main/java/com/aespa/nextplace/service/UserService.java, backend/src/main/java/com/aespa/nextplace/service/UserServiceImpl.java, backend/src/main/java/com/aespa/nextplace/util/CookieUtil.java, backend/src/main/java/com/aespa/nextplace/util/FirebaseTokenFilter.java
- 프론트 테스트용 임시 토큰 발급
<br>
- 프론트 유니티 환경에서 로그인 없이 테스트를 위한 토큰 제공과 필터 수정입니다.
<br>
- 이번 이슈에서 작업한 내용물은 프론트에서 확인이 끝나면 모두 다시 제거하겠습니다
=> test:[#97] 프론트 테스트용 임시 토큰 발급

backend/src/main/java/com/aespa/nextplace/controller/PladexController.java, backend/src/main/java/com/aespa/nextplace/controller/PlamonController.java, backend/src/main/java/com/aespa/nextplace/model/response/ErrorResponse.java
- Auth가 구현되어서 기존 임시 구현에 Authorization 검증을 추가했습니다
<br>
- servlet request에서 uid를 추출하는 방식으로 변경했습니다
- 기존 구현했던 요청들에 api docs를 위한 @Content를 추가했습니다
<br>
- 로그인 테스트를 위해서 서버로 요청 어떻게 보내야하나용??
=> Close #101 - 캐릭터 도메인에 Authorization 추가

backend/build.gradle, backend/src/main/java/com/aespa/nextplace/NextplaceApplication.java, backend/src/main/java/com/aespa/nextplace/model/request/PlactionRequest.java, backend/src/main/java/com/aespa/nextplace/model/request/PladexRequest.java, backend/src/main/java/com/aespa/nextplace/model/request/PlamonChangeMainRequest.java, backend/src/main/java/com/aespa/nextplace/model/request/PlamonLevelUpRequest.java, backend/src/main/java/com/aespa/nextplace/util/LoggingAspect.java
- Service의 메서드가 호출될 때 로그를 기록하려 했습니다
<br>
- `com.aespa.nextplace.service` 패키지 내부 메서드에 AOP를 적용하여 logging을 적용했습니다
- log level은 info로 설정했습니다
- 다음과 같은 로그가 콘솔에 표시됩니당
```
2021-11-16 00:59:21.544  INFO 10584 --- [nio-8080-exec-5] com.aespa.nextplace.util.LoggingAspect   : 실행 메서드 : loadUserByUsername 전달 파라미터 : [12345] 클래스: com.aespa.nextplace.service.MyUserDetailsService
2021-11-16 00:59:21.777  INFO 10584 --- [nio-8080-exec-5] com.aespa.nextplace.util.LoggingAspect   : 실행 메서드 : savePladex 전달 파라미터 : [PladexRequest(name=실험몬, information=어느 대학원생이 랩실에 혼자 남아 실험을 하다가 몬스터가 되었다는 소문이 있다, rank=R)] 클래스: com.aespa.nextplace.service.PladexServiceImpl
```
<br>
- application profile을 적용하면 개발 환경 별로 분리하여 log를 기록하거나 저장할 수 있을 것 같습니다
- application.yml에 다음과 같은 코드를 첨부해야 합니다
```yml
logging:
level:
root: info
```
=> Close #105 - 메서드 로깅

backend/src/main/java/com/aespa/nextplace/model/repository/PladexRepository.java
- 캐릭터 뽑기 시 기본캐릭터를 뽑을 수 있는 버그를 발견했습니다
<br>
- 캐릭터를 뽑기 위해 랭크 별 Pladex 리스트를 조회할 때 기본캐릭터를 제외하도록 수정했습니다
=> Close #108 - 캐릭터 뽑기 시 기본캐릭터 획득 버그 수정

backend/src/main/java/com/aespa/nextplace/controller/PlamonController.java
- Unity에서 HTTP Method - PATCH 지원 안 함
<br>
- PATCH 메서드를 PUT으로 변경했습니다
=> Close #130 - Method를 PATCH에서 PUT으로 수정

backend/src/main/java/com/aespa/nextplace/model/repository/PlamonRepository.java, backend/src/main/java/com/aespa/nextplace/service/PlamonServiceImpl.java, backend/src/test/java/com/aespa/nextplace/plamon/PlamonServiceTest.java
- 보유한 캐릭터가 없을 경우 맨 처음 뽑은 캐릭터를 대표 캐릭터로 선정한다
<br>
- 보유한 캐릭터가 하나도 없을 경우에는 처음 뽑기로 얻은 캐릭터를 대표 캐릭터로 지정한다
=> Close #126 - 처음 뽑은 캐릭터를 대표 캐릭터로 지정한다

README.md
- 리드미 작성
<br>
- 리드미가 바뀌었습니다
<br>
- 수고하셨습니다
=> Close #4 - Feature/readme
